version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: diet-logger-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diet-logger
    ports:
      - "5432:5432"
    volumes:
      - diet_logger_data:/var/lib/postgresql/data

volumes:
  diet_logger_data:
